import nimibook

var nimWikiBook = newBookFromToc("Nim Wiki", "nimwiki"):
  section("Home", "Home"):
    entry("Best practices", "Best_practices.nim")
    entry("Bioconda", "Bioconda.nim")
    entry("Common Criticisms", "Common_Criticisms.nim")
    entry("Community Guidelines (Proposal)", "Community_Guidelines_Proposal.nim")
    entry("Community Projects", "Community_Projects.nim")
    entry("Companies using Nim", "Companies_using_Nim.nim")
    entry("Compiler module reference", "Compiler_module_reference.nim")
    entry("Consts defined by the compiler", "Consts_defined_by_the_compiler.nim")
    entry("Creating a release", "Creating_a_release.nim")
    entry("CudaText", "CudaText.nim")
    entry("Curated Packages", "Curated_Packages.nim")
    entry("Debugging the compiler", "Debugging_the_compiler.nim")
    entry("Editor Support", "Editor_Support.nim")
    entry("FOSDEM 2018", "FOSDEM_2018.nim")
    entry("Fuzzing your nim code to rabbit out all the hard bugs", "Fuzzing_your_nim_code_to_rabbit_out_all_the_hard_bugs.nim")
    entry("GSoC 2014 Ideas", "GSoC_2014_Ideas.nim")
    entry("GSoC 2015 Ideas", "GSoC_2015_Ideas.nim")
    entry("GSoC 2016 Ideas", "GSoC_2016_Ideas.nim")
    entry("Getting Started", "Getting_Started.nim")
    entry("GitLab CI setup", "GitLab_CI_setup.nim")
    entry("Hunting leaks", "Hunting_leaks.nim")
    entry("IRC guidelines", "IRC_guidelines.nim")
    entry("Lesser known Nim features", "Lesser_known_Nim_features.nim")
    entry("Meeting Notes", "Meeting_Notes.nim")
  section("Nim for X programmers", "Nim_for_X_programmers"):
    entry("Nim for C programmers", "Nim_for_C_programmers.nim")
    entry("Nim for Haskell Programmers", "Nim_for_Haskell_Programmers.nim")
    entry("Nim for Java programmers", "Nim_for_Java_programmers.nim")
    entry("Nim for Python Programmers", "Nim_for_Python_Programmers.nim")
    entry("Nim for TypeScript Programmers", "Nim_for_TypeScript_Programmers.nim")
    entry("Official branches", "Official_branches.nim")
    entry("Organizations using Nim", "Organizations_using_Nim.nim")
    entry("Playing with CPP-VTABLE from Nim", "Playing_with_CPP__VTABLE_from_Nim.nim")
    entry("Pygments issues", "Pygments_issues.nim")
    entry("Quick Start 2018", "Quick_Start_2018.nim")
    entry("'Run nim source files like scripts (with tcc and binfmt_misc)", "Run_nim_source_files_like_scripts_with_tcc_and_binfmt_misc.nim")
    entry("Standard library and the JavaScript backend", "Standard_library_and_the_JavaScript_backend.nim")
    entry("'Status of gc:arc and gc:orc (library compatibility)", "Status_of_gc:arc_and_gc:orc_library_compatibility.nim")
    entry("Style Guide for Nim Code", "Style_Guide_for_Nim_Code.nim")
    entry("Templates", "Templates.nim")
    entry("Tips and tricks", "Tips_and_tricks.nim")
    entry("Tutorial: Hacking the Nim compiler: Pragmas", "Tutorial:_Hacking_the_Nim_compiler:_Pragmas.nim")
    entry("Unofficial FAQ", "Unofficial_FAQ.nim")
    entry("Using nimscript for configuration", "Using_nimscript_for_configuration.nim")
    entry("Whitespace FAQ", "Whitespace_FAQ.nim")
    entry("Writing a Macro", "Writing_a_Macro.nim")
    entry("_Sidebar", "Sidebar.nim")
  section("Spanish", "Spanish_wiki_toc"):
    entry("Aprende Nim en 5 Minutos", "Aprende_Nim_en_5_Minutos.nim")
    entry("Nim for Python Programmers ES", "Nim_for_Python_Programmers_ES.nim")

nimibookCli(nimWikiBook)
